package de.unibonn.simpleml.validation.codes

enum class ErrorCode {
    AttributeMustHaveType,
    ParameterMustHaveType,
    ResultMustHaveType,

    CLASS_MUST_HAVE_UNIQUE_INHERITED_MEMBERS,
    CLASS_MUST_HAVE_UNIQUE_PARENT_TYPES,
    CLASS_MUST_INHERIT_ONLY_CLASSES,
    CLASS_MUST_NOT_BE_SUBTYPE_OF_ITSELF,
    REDECLARATION,

    FILE_MUST_DECLARE_PACKAGE,
    FILE_MUST_HAVE_ONLY_ONE_PACKAGE,
    PACKAGE_MUST_COME_FIRST,
    STUB_FILE_MUST_NOT_DECLARE_WORKFLOWS,
    WORKFLOW_FILE_MUST_ONLY_DECLARE_WORKFLOWS_AND_WORKFLOW_STEPS,

    ANNOTATION_IS_SINGLE_USE,
    DEPRECATED_REQUIRED_PARAMETER,

    UNRESOLVED_IMPORTED_NAMESPACE,
    WILDCARD_IMPORT_WITH_ALIAS,

    NO_REQUIRED_PARAMETERS_AFTER_FIRST_OPTIONAL_PARAMETER,

    NO_YIELD_IN_WORKFLOW,

    CONTEXT_OF_CALL_WITHOUT_RESULTS,
    CONTEXT_OF_CALL_WITH_MANY_RESULTS,
    NO_RECURSION,
    RECEIVER_MUST_BE_CALLABLE,
    CALLED_CLASS_MUST_HAVE_CONSTRUCTOR,
    CALLED_ENUM_VARIANT_MUST_HAVE_CONSTRUCTOR,

    INSTANCE_METHOD_MUST_BE_CALLED,

    MISSING_REQUIRED_PARAMETER,
    NO_POSITIONAL_ARGUMENTS_AFTER_FIRST_NAMED_ARGUMENT,
    TOO_MANY_ARGUMENTS,
    UNIQUE_PARAMETERS,

    MISSING_REQUIRED_TYPE_PARAMETER,
    NO_POSITIONAL_TYPE_ARGUMENTS_AFTER_FIRST_NAMED_TYPE_ARGUMENT,

    ASSIGNEE_WITHOUT_VALUE,

    MISSING_TYPE_ARGUMENT_LIST,

    UNION_TYPE_WITHOUT_TYPE_ARGUMENTS,

    NON_STATIC_PROPAGATES,
    PURE_PROPAGATES,
    STATIC_PROPAGATES,

    REDECLARATION_IN_OTHER_FILE,

    MISSING_ARGUMENT_LIST,
    WRONG_TARGET,
}
