# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation

# General Config
APPLY_FIXES: all
DEFAULT_BRANCH: main
FILEIO_REPORTER: false
IGNORE_GITIGNORED_FILES: true
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

# Language-specific
JAVASCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_DEFAULT_STYLE: prettier

# Linters
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_CSPELL
  - SPELL_MISSPELL
