# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

# General Config
APPLY_FIXES: all
DEFAULT_BRANCH: main
FILEIO_REPORTER: false
IGNORE_GITIGNORED_FILES: true
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_EXCLUDE: "(\.localhost|github.com)"

# Language-specific
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .js
  - .jsx
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .ts
  - .tsx

# Linters
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_CSPELL
  - SPELL_MISSPELL
