/*
 * generated by Xtext 2.23.0
 */
package de.unibonn.simpleml.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class SimpleMLWebModule extends AbstractSimpleMLWebModule {
}
