/**
 * generated by Xtext 2.23.0
 */
package de.unibonn.simpleml.ide;

import de.unibonn.simpleml.ide.AbstractSimpleMLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SimpleMLIdeModule extends AbstractSimpleMLIdeModule {
}
