/**
 * generated by Xtext 2.23.0
 */
package de.unibonn.simpleml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.unibonn.simpleml.SimpleMLRuntimeModule;
import de.unibonn.simpleml.SimpleMLStandaloneSetup;
import de.unibonn.simpleml.ide.SimpleMLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SimpleMLIdeSetup extends SimpleMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    SimpleMLRuntimeModule _simpleMLRuntimeModule = new SimpleMLRuntimeModule();
    SimpleMLIdeModule _simpleMLIdeModule = new SimpleMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_simpleMLRuntimeModule, _simpleMLIdeModule));
  }
}
