PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sml: <https://simple-ml.de/resource/>
PREFIX csvw: <http://www.w3.org/ns/csvw#>

SELECT ?identifier ?property ?domain ?valueType ?identifier ?columnIndex ?subjectClass
 (STR(?propertyLabelWithLang) AS ?propertyLabel)
 (STR(?subjectClassLabelWithLang) AS ?subjectClassLabel)
WHERE {

?dataset a dcat:Dataset .
?dataset dcterms:identifier "@datasetId@" .

?dataset sml:hasAttribute ?attribute .

?attribute dcterms:identifier ?identifier .
?attribute sml:mapsToProperty ?property .
?attribute sml:mapsToDomain ?domain .
?attribute sml:valueType ?valueType .
?attribute dcterms:identifier ?identifier .
?attribute sml:columnIndex ?columnIndex .

?property rdfs:label ?propertyLabelWithLang .
FILTER(LANG(?propertyLabelWithLang) = "@lang@") .

?domain sml:mapsTo ?subjectClass .
?subjectClass rdfs:label ?subjectClassLabelWithLang.
FILTER(LANG(?subjectClassLabelWithLang) = "@lang@") .

} ORDER BY ?columnIndex