<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simpleML"
                nsURI="http://www.unibonn.de/simpleml/SimpleML" nsPrefix="simpleML">

    <eClassifiers xsi:type="ecore:EClass"
                  name="SmlAbstractElement"
                  abstract="true"
    >
        <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
                             eType="#//SmlAnnotationUse" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractDeclaration" abstract="true"
                  eSuperTypes="#//SmlAbstractElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="annotationHolder" eType="#//SmlAnnotationUseHolder"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractLocalVariable" abstract="true"
                  eSuperTypes="#//SmlAbstractDeclaration"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractNamedTypeDeclaration" abstract="true"
                  eSuperTypes="#//SmlAbstractDeclaration"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAnnotation" eSuperTypes="#//SmlAbstractDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAnnotationUseHolder" eSuperTypes="#//SmlAbstractElement"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAnnotationUse">
        <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" eType="#//SmlAnnotation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//SmlArgumentList"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAttribute" eSuperTypes="#//SmlAbstractDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="static"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlAbstractType"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass"
                  name="SmlClass"
                  abstract="false"
                  eSuperTypes="#//SmlAbstractNamedTypeDeclaration"
    >
        <eStructuralFeatures xsi:type="ecore:EReference"
                             name="typeParameterList"
                             eType="#//SmlTypeParameterList"
                             containment="true"
        />
        <eStructuralFeatures xsi:type="ecore:EReference"
                             name="parameterList"
                             eType="#//SmlParameterList"
                             containment="true"
        />
        <eStructuralFeatures xsi:type="ecore:EReference"
                             name="parentTypeList"
                             eType="#//SmlParentTypeList"
                             containment="true"
        />
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterConstraintList"
                             eType="#//SmlTypeParameterConstraintList" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlClassBody"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlClassBody">
        <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
                             eType="#//SmlAbstractElement" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlCompilationUnit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
                             eType="#//SmlAbstractElement" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlPackage" eSuperTypes="#//SmlAbstractDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
                             eType="#//SmlImport" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
                             eType="#//SmlAbstractElement" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlImport">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="alias" eType="#//SmlImportAlias" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlImportAlias">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlEnum" eSuperTypes="#//SmlAbstractNamedTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlEnumBody"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlEnumBody">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
                             eType="#//SmlEnumVariant" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlEnumVariant" eSuperTypes="#//SmlAbstractNamedTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterList" eType="#//SmlTypeParameterList"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterConstraintList"
                             eType="#//SmlTypeParameterConstraintList" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlFunction" eSuperTypes="#//SmlAbstractDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="static"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterList" eType="#//SmlTypeParameterList"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="resultList" eType="#//SmlResultList"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterConstraintList"
                             eType="#//SmlTypeParameterConstraintList" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlParameterList">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
                             eType="#//SmlParameter" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlParameter" eSuperTypes="#//SmlAbstractLocalVariable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//SmlAbstractExpression"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlAbstractType"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="variadic"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlResultList">
        <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
                             eType="#//SmlResult" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlResult" eSuperTypes="#//SmlAbstractDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlAbstractType"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlWorkflow" eSuperTypes="#//SmlAbstractDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlBlock"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlWorkflowStep" eSuperTypes="#//SmlAbstractDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="resultList" eType="#//SmlResultList"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlBlock"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlBlock">
        <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
                             eType="#//SmlAbstractStatement" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractStatement" abstract="true"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAssignment" eSuperTypes="#//SmlAbstractStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="assigneeList" eType="#//SmlAssigneeList"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SmlAbstractExpression"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAssigneeList">
        <eStructuralFeatures xsi:type="ecore:EReference" name="assignees" upperBound="-1"
                             eType="#//SmlAbstractAssignee" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractAssignee" abstract="true"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlPlaceholder"
                  eSuperTypes="#//SmlAbstractAssignee #//SmlAbstractLocalVariable"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlWildcard" eSuperTypes="#//SmlAbstractAssignee"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlYield" eSuperTypes="#//SmlAbstractAssignee">
        <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//SmlResult"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlLambdaYield"
                  eSuperTypes="#//SmlAbstractDeclaration #//SmlAbstractAssignee"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlExpressionStatement" eSuperTypes="#//SmlAbstractStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SmlAbstractExpression"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractExpression" abstract="true"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractLiteral" abstract="true"
                  eSuperTypes="#//SmlAbstractExpression"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlBoolean" eSuperTypes="#//SmlAbstractLiteral">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="true"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractNumber" abstract="true" eSuperTypes="#//SmlAbstractLiteral"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlFloat" eSuperTypes="#//SmlAbstractNumber">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlInt" eSuperTypes="#//SmlAbstractNumber">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlString" eSuperTypes="#//SmlAbstractLiteral">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlTemplateString" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
                             eType="#//SmlAbstractExpression" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlTemplateStringPart" eSuperTypes="#//SmlAbstractLiteral">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlLambda" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlBlock"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlInfixOperation" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//SmlAbstractExpression"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//SmlAbstractExpression"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlNull" eSuperTypes="#//SmlAbstractLiteral"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlPrefixOperation" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//SmlAbstractExpression"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlReference" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="#//SmlAbstractDeclaration"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlParenthesizedExpression" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SmlAbstractExpression"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractChainedExpression" abstract="true"
                  eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="#//SmlAbstractExpression"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlCall" eSuperTypes="#//SmlAbstractChainedExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//SmlArgumentList"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeArgumentList" eType="#//SmlTypeArgumentList"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlArgumentList">
        <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
                             eType="#//SmlArgument" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlArgument" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//SmlParameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SmlAbstractExpression"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlMemberAccess" eSuperTypes="#//SmlAbstractChainedExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="#//SmlReference"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullSafe"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractType" abstract="true"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlCallableType" eSuperTypes="#//SmlAbstractType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="resultList" eType="#//SmlResultList"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlMemberType" eSuperTypes="#//SmlAbstractType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="#//SmlNamedType"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="#//SmlAbstractType"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlNamedType" eSuperTypes="#//SmlAbstractType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="#//SmlAbstractNamedTypeDeclaration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeArgumentList" eType="#//SmlTypeArgumentList"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlParenthesizedType" eSuperTypes="#//SmlAbstractType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlAbstractType"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlUnionType" eSuperTypes="#//SmlAbstractType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeArgumentList" eType="#//SmlTypeArgumentList"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlParentTypeList">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parentTypes" upperBound="-1"
                             eType="#//SmlAbstractType" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameterList">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
                             eType="#//SmlTypeParameter" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameter" eSuperTypes="#//SmlAbstractNamedTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="variance"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameterConstraintList">
        <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
                             eType="#//SmlTypeParameterConstraint" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameterConstraint">
        <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//SmlTypeParameter"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//SmlAbstractType"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeArgumentList">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
                             eType="#//SmlTypeArgument" containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeArgument">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameter" eType="#//SmlTypeParameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SmlAbstractTypeArgumentValue"
                             containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractTypeArgumentValue" abstract="true"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlStarProjection" eSuperTypes="#//SmlAbstractTypeArgumentValue"/>

    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeProjection" eSuperTypes="#//SmlAbstractTypeArgumentValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlAbstractType"
                             containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="variance"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
</ecore:EPackage>
