<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simpleML" nsURI="http://www.unibonn.de/simpleml/SimpleML" nsPrefix="simpleML">
  <eClassifiers xsi:type="ecore:EClass" name="SmlDeclaration" abstract="false">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//SmlAnnotationUse" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotationHolder" eType="#//SmlAnnotationHolder"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifiers" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlLocalVariable" abstract="true" eSuperTypes="#//SmlDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlNamedTypeDeclaration" abstract="true"
      eSuperTypes="#//SmlDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlAnnotationHolder" eSuperTypes="#//SmlDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlAnnotation" eSuperTypes="#//SmlDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlAnnotationUse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" eType="#//SmlAnnotation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//SmlArgumentList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlAttribute" eSuperTypes="#//SmlDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlClass" abstract="false" eSuperTypes="#//SmlNamedTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterList" eType="#//SmlTypeParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentTypeList" eType="#//SmlParentTypeList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterConstraintList"
        eType="#//SmlTypeParameterConstraintList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlClassBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlClassBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//SmlDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlCompilationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//SmlImport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//SmlDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alias" eType="#//SmlImportAlias" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlImportAlias">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlEnum" eSuperTypes="#//SmlNamedTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlEnumBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlEnumBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
        eType="#//SmlEnumVariant" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlEnumVariant" eSuperTypes="#//SmlNamedTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterList" eType="#//SmlTypeParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterConstraintList"
        eType="#//SmlTypeParameterConstraintList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlFunction" eSuperTypes="#//SmlDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterList" eType="#//SmlTypeParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultList" eType="#//SmlResultList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterConstraintList"
        eType="#//SmlTypeParameterConstraintList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//SmlParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlParameter" eSuperTypes="#//SmlLocalVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//SmlExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vararg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlResultList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//SmlResult" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlResult" eSuperTypes="#//SmlDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlWorkflow" eSuperTypes="#//SmlDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlWorkflowStep" eSuperTypes="#//SmlDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultList" eType="#//SmlResultList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//SmlStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlStatement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlAssignment" eSuperTypes="#//SmlStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assigneeList" eType="#//SmlAssigneeList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SmlExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlAssigneeList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignees" upperBound="-1"
        eType="#//SmlAssignee" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlAssignee" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlPlaceholder" eSuperTypes="#//SmlAssignee #//SmlLocalVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlWildcard" eSuperTypes="#//SmlAssignee"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlYield" eSuperTypes="#//SmlAssignee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//SmlResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlLambdaYield" eSuperTypes="#//SmlDeclaration #//SmlAssignee"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlExpressionStatement" eSuperTypes="#//SmlStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SmlExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlExpression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlLiteral" abstract="true" eSuperTypes="#//SmlExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlBoolean" eSuperTypes="#//SmlLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlNumber" abstract="true" eSuperTypes="#//SmlLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlFloat" eSuperTypes="#//SmlNumber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlInt" eSuperTypes="#//SmlNumber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlString" eSuperTypes="#//SmlLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlTemplateString" eSuperTypes="#//SmlExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//SmlExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlTemplateStringPart" eSuperTypes="#//SmlLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlLambda" eSuperTypes="#//SmlExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlInfixOperation" eSuperTypes="#//SmlExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//SmlExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//SmlExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlNull" eSuperTypes="#//SmlLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlPrefixOperation" eSuperTypes="#//SmlExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//SmlExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlReference" eSuperTypes="#//SmlExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="#//SmlDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlParenthesizedExpression" eSuperTypes="#//SmlExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SmlExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlChainedExpression" abstract="true"
      eSuperTypes="#//SmlExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="#//SmlExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlCall" eSuperTypes="#//SmlChainedExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//SmlArgumentList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArgumentList" eType="#//SmlTypeArgumentList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlArgumentList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//SmlArgument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlArgument" eSuperTypes="#//SmlExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//SmlParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SmlExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlMemberAccess" eSuperTypes="#//SmlChainedExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="#//SmlReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlCallableType" eSuperTypes="#//SmlType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultList" eType="#//SmlResultList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlMemberType" eSuperTypes="#//SmlType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="#//SmlNamedType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="#//SmlType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlNamedType" eSuperTypes="#//SmlType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="#//SmlNamedTypeDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArgumentList" eType="#//SmlTypeArgumentList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlParenthesizedType" eSuperTypes="#//SmlType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlUnionType" eSuperTypes="#//SmlType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArgumentList" eType="#//SmlTypeArgumentList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlParentTypeList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentTypes" upperBound="-1"
        eType="#//SmlType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
        eType="#//SmlTypeParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameter" eSuperTypes="#//SmlNamedTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameterConstraintList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//SmlTypeParameterConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameterConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//SmlTypeParameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//SmlType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlTypeArgumentList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
        eType="#//SmlTypeArgument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlTypeArgument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameter" eType="#//SmlTypeParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SmlTypeArgumentValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmlTypeArgumentValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlStarProjection" eSuperTypes="#//SmlTypeArgumentValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmlTypeProjection" eSuperTypes="#//SmlTypeArgumentValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
