PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sml: <https://simple-ml.de/resource/>
PREFIX csvw: <http://www.w3.org/ns/csvw#>

SELECT ?identifier (STR(?regionURI) AS ?region) ?instances
WHERE {
    ?dataset a dcat:Dataset .
    ?dataset dcterms:identifier "@datasetId@" .
    ?dataset sml:hasAttribute ?attribute .

    ?attribute dcterms:identifier ?identifier .

    ?attribute sml:hasSpatialDistribution [
        sml:spatialDistributionValue [
            sml:instancesOfRegion ?regionURI ;
            sml:numberOfInstancesInRegion ?instances ;
        ]
    ] .
} ORDER BY ?attribute