PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sml: <https://simple-ml.de/resource/>
PREFIX csvw: <http://www.w3.org/ns/csvw#>

SELECT ?content  WHERE
{
{
SELECT (-1 AS ?rank) ?content
WHERE {

    ?dataset a dcat:Dataset .
    ?dataset dcterms:identifier "@datasetId@" .
    ?dataset sml:hasSample ?sample .

    ?sample sml:hasHeader [
        sml:hasContent ?content ;
    ] .


}
}
UNION {
SELECT ?rank ?content
WHERE {

    ?dataset a dcat:Dataset .
    ?dataset dcterms:identifier "@datasetId@" .
    ?dataset sml:hasSample ?sample .

    ?sample sml:hasLine [
        sml:hasContent ?content ;
        sml:rank ?rank
    ] .


}
}
} ORDER BY ?rank