/**
 * generated by Xtext 2.23.0
 */
package de.unibonn.simpleml.validation;

import de.unibonn.simpleml.validation.AbstractSimpleMLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SimpleMLValidator extends AbstractSimpleMLValidator {
}
