/**
 * generated by Xtext 2.23.0
 */
package de.unibonn.simpleml.web;

import de.unibonn.simpleml.web.AbstractSimpleMLWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class SimpleMLWebModule extends AbstractSimpleMLWebModule {
}
