/**
 * generated by Xtext 2.23.0
 */
package de.unibonn.simpleml.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.unibonn.simpleml.SimpleMLRuntimeModule;
import de.unibonn.simpleml.SimpleMLStandaloneSetup;
import de.unibonn.simpleml.ide.SimpleMLIdeModule;
import de.unibonn.simpleml.web.SimpleMLWebModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class SimpleMLWebSetup extends SimpleMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    SimpleMLRuntimeModule _simpleMLRuntimeModule = new SimpleMLRuntimeModule();
    SimpleMLIdeModule _simpleMLIdeModule = new SimpleMLIdeModule();
    SimpleMLWebModule _simpleMLWebModule = new SimpleMLWebModule();
    return Guice.createInjector(Modules2.mixin(_simpleMLRuntimeModule, _simpleMLIdeModule, _simpleMLWebModule));
  }
}
