numberOfNullValues = 'numberOfNullValues'
decile = 'decile'
quartile = 'quartile'
averageNumberOfSpecialCharacters = 'averageNumberOfSpecialCharacters'
averageNumberOfTokens = 'averageNumberOfTokens'
numberOfValidValues = 'numberOfValidValues'
numberOfOutliersBelow = 'numberOfOutliersBelow'
averageNumberOfCapitalisedValues = 'averageNumberOfCapitalisedValues'
averageNumberOfDigits = 'averageNumberOfDigits'
numberOfOutliersAbove = 'numberOfOutliersAbove'
numberOfDistinctValues = 'numberOfDistinctValues'
histogram = 'histogram'
averageNumberOfCharacters = 'averageNumberOfCharacters'
median = 'median'
numberOfValues = 'numberOfValues'
mean = 'mean'
numberOfValidNonNullValues = 'numberOfValidNonNullValues'
maximum = 'maximum'
minimum = 'minimum'
standardDeviation = 'standardDeviation'
numberOfInvalidValues = 'numberOfInvalidValues'

value = 'value'
values = 'values'

valueDistribution = 'valueDistribution'
numberOfInstances = 'numberOfInstances'
bucketMinimum = 'bucketMinimum'
bucketMaximum = 'bucketMaximum'
bucketValue = 'value'

sample = 'sample_instances'
sample_header_labels = 'header_labels'
sample_lines = 'lines'

