name: stdlib
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - conda-build=3.21.4
  - geopandas=0.8.1
  - numpy=1.21.0
  - pandas=1.3.0
  - pyproj=3.1.0
  - rdflib=5.0.0
  - scikit-learn=0.24.2
  - shapely=1.7.1
  - sparqlwrapper=1.8.5