PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sml: <https://simple-ml.de/resource/>
PREFIX csvw: <http://www.w3.org/ns/csvw#>

SELECT (GROUP_CONCAT(DISTINCT ?subject; SEPARATOR = ";") AS ?subjects) (STR(?titleWithLang) AS ?title) ?fileLocation ?nullValue ?hasHeader ?separator WHERE {
?dataset a dcat:Dataset .
?dataset dcterms:identifier "@datasetId@" .

OPTIONAL {
    ?dataset dcterms:subject ?subject .
    FILTER LANGMATCHES(LANG(?subject),"@lang@") .
}

OPTIONAL {
    ?dataset dcterms:title ?titleWithLang .
    FILTER LANGMATCHES(LANG(?titleWithLang),"@lang@") .
}

?dataset sml:hasFile ?file .
?file sml:fileLocation ?fileLocation .

?file csvw:null ?nullValue .
?file csvw:header ?hasHeader .
?file csvw:separator ?separator .
# ?file dcterms:format ?format .

} GROUP BY ?dataset ?titleWithLang ?fileLocation ?nullValue ?hasHeader ?separator