PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sml: <https://simple-ml.de/resource/>

SELECT ?dataset ?identifier (GROUP_CONCAT(DISTINCT ?subject; SEPARATOR = ";") AS ?subjects) (STR(?titleWithLang) AS ?title) ?numberOfInstances WHERE {

#domainFilter ?catalog a dcat:Catalog .
#domainFilter ?catalog dcterms:subject "@domain@"@@lang@ .
#domainFilter ?catalog dcat:dataset ?dataset .

?dataset a dcat:Dataset .
?dataset dcterms:identifier ?identifier .
?dataset dcterms:subject ?subject .
?dataset dcterms:title ?titleWithLang .
?dataset sml:numberOfInstances ?numberOfInstances .
FILTER (datatype(?numberOfInstances) = xsd:nonNegativeInteger) .

#topicFilter FILTER EXISTS { ?dataset dcterms:subject "@topic@"@@lang@ } .

FILTER LANGMATCHES(LANG(?subject),"@lang@") .
FILTER LANGMATCHES(LANG(?titleWithLang),"@lang@") .
} GROUP BY ?dataset ?titleWithLang ?identifier ?numberOfInstances