PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sml: <https://simple-ml.de/resource/>
PREFIX csvw: <http://www.w3.org/ns/csvw#>
PREFIX seas: <https://w3id.org/seas/>

SELECT ?identifier ?value ?rank ?evalType

WHERE {

    ?dataset a dcat:Dataset .
    ?dataset dcterms:identifier "@datasetId@" .
    ?dataset sml:hasAttribute ?attribute .

    ?attribute dcterms:identifier ?identifier .
    ?attribute seas:evaluation ?eval .
    ?eval seas:evaluatedValue ?value .

    ?eval rdf:type ?type .
    ?type dcterms:identifier ?evalType .

    OPTIONAL {
        ?eval seas:rank ?rank .
    }

} ORDER BY ?identifier ?evalType ?rank