name: Pull Request Format

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check-title:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    concurrency:
      group: ${{ github.head_ref }}__pr-format__check-title
      cancel-in-progress: true

    steps:
      - uses: amannn/action-semantic-pull-request@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
